basePath: /api
definitions:
  domain.BuildInfo:
    properties:
      build_number:
        type: string
      bundle_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      file_size:
        type: integer
      icon:
        type: string
      platform:
        $ref: '#/definitions/domain.Platform'
      title:
        type: string
      upload_id:
        type: string
      version:
        type: string
    type: object
  domain.Platform:
    enum:
    - ios
    - android
    type: string
    x-enum-varnames:
    - IOS
    - Android
  interfaces.DownloadResponse:
    properties:
      build_number:
        type: string
      bundle_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      file_size:
        type: integer
      icon:
        type: string
      platform:
        $ref: '#/definitions/domain.Platform'
      qr_code:
        type: string
      title:
        type: string
      upload_id:
        type: string
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for distributing mobile applications.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: App Distribution API
  version: "1.0"
paths:
  /apps:
    get:
      description: Get a list of all available applications.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.BuildInfo'
            type: array
        "500":
          description: Failed to get apps
          schema:
            type: string
      summary: List all apps
      tags:
      - apps
  /apps/{bundle_id}:
    get:
      description: Get a download link for the latest version of an app.
      parameters:
      - description: Bundle ID of the app
        in: path
        name: bundle_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.DownloadResponse'
        "400":
          description: Invalid URL
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get latest app version
      tags:
      - apps
  /apps/{bundle_id}/versions:
    get:
      description: Get all versions of an app.
      parameters:
      - description: Bundle ID of the app
        in: path
        name: bundle_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.BuildInfo'
            type: array
        "400":
          description: Invalid URL
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all app versions
      tags:
      - apps
  /apps/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a new .apk or .ipa file.
      parameters:
      - description: Application file (.apk or .ipa)
        in: formData
        name: app_file
        required: true
        type: file
      - description: Bundle ID (for .ipa)
        in: formData
        name: bundle_id
        type: string
      - description: Version (for .ipa)
        in: formData
        name: version
        type: string
      - description: Build Number (for .ipa)
        in: formData
        name: build_number
        type: string
      - description: Title (for .ipa)
        in: formData
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BuildInfo'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload a new app
      tags:
      - apps
swagger: "2.0"
