networks:
  app-net:
    driver: bridge

services:
  # The frontend web application
  web:
    build:
      context: ./web_app
      args:
        # You can pass the API URL to your frontend build like this:
        # This URL is used by the browser, so it must be accessible from the host.
        - API_URL=http://go-api:8080
    container_name: app-distribution-web-app
    ports:
      - "3000:3000"
    # The web app depends on the API being available
    depends_on:
      - go-api
    restart: unless-stopped
    networks:
      - app-net

  # The Go backend API server
  go-api:
    build:
      context: ./go_server
    container_name: app-distribution-go-server
    ports:
      - "8080:8080"
    volumes:
      - ./go_uploads:/storage
    environment:
      - API_HOST=localhost:8081
    restart: unless-stopped
    networks:
      - app-net
